version: "3.8"

services:
  nextjs:
    # This uses either a pre-built image (if IMAGE_NAME is defined)
    # or builds locally using the Dockerfile if IMAGE_NAME is unset
    image: ${IMAGE_NAME:-}
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_TRUST_HOST=${NEXTAUTH_TRUST_HOST}
      - AUTH_SECRET=${AUTH_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - HOST_URL=${HOST_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}

    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
